/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPayRouteImport } from './routes/_authenticated/pay'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedAchievementsIndexRouteImport } from './routes/_authenticated/achievements/index'
import { Route as publicTermsIndexRouteImport } from './routes/(public)/terms/index'
import { Route as publicRegisterIndexRouteImport } from './routes/(public)/register/index'
import { Route as publicPrivacyIndexRouteImport } from './routes/(public)/privacy/index'
import { Route as publicPaymentsIndexRouteImport } from './routes/(public)/payments/index'
import { Route as publicLoginIndexRouteImport } from './routes/(public)/login/index'
import { Route as publicLeaderboardIndexRouteImport } from './routes/(public)/leaderboard/index'
import { Route as publicCookiesIndexRouteImport } from './routes/(public)/cookies/index'
import { Route as publicContactIndexRouteImport } from './routes/(public)/contact/index'
import { Route as publicUUsernameIndexRouteImport } from './routes/(public)/u.$username/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayRoute = AuthenticatedPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAchievementsIndexRoute =
  AuthenticatedAchievementsIndexRouteImport.update({
    id: '/achievements/',
    path: '/achievements/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const publicTermsIndexRoute = publicTermsIndexRouteImport.update({
  id: '/(public)/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRegisterIndexRoute = publicRegisterIndexRouteImport.update({
  id: '/(public)/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPrivacyIndexRoute = publicPrivacyIndexRouteImport.update({
  id: '/(public)/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPaymentsIndexRoute = publicPaymentsIndexRouteImport.update({
  id: '/(public)/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginIndexRoute = publicLoginIndexRouteImport.update({
  id: '/(public)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLeaderboardIndexRoute = publicLeaderboardIndexRouteImport.update({
  id: '/(public)/leaderboard/',
  path: '/leaderboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicCookiesIndexRoute = publicCookiesIndexRouteImport.update({
  id: '/(public)/cookies/',
  path: '/cookies/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicContactIndexRoute = publicContactIndexRouteImport.update({
  id: '/(public)/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicUUsernameIndexRoute = publicUUsernameIndexRouteImport.update({
  id: '/(public)/u/$username/',
  path: '/u/$username/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/pay': typeof AuthenticatedPayRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/contact/': typeof publicContactIndexRoute
  '/cookies/': typeof publicCookiesIndexRoute
  '/leaderboard/': typeof publicLeaderboardIndexRoute
  '/login/': typeof publicLoginIndexRoute
  '/payments/': typeof publicPaymentsIndexRoute
  '/privacy/': typeof publicPrivacyIndexRoute
  '/register/': typeof publicRegisterIndexRoute
  '/terms/': typeof publicTermsIndexRoute
  '/achievements/': typeof AuthenticatedAchievementsIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/u/$username/': typeof publicUUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/pay': typeof AuthenticatedPayRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/contact': typeof publicContactIndexRoute
  '/cookies': typeof publicCookiesIndexRoute
  '/leaderboard': typeof publicLeaderboardIndexRoute
  '/login': typeof publicLoginIndexRoute
  '/payments': typeof publicPaymentsIndexRoute
  '/privacy': typeof publicPrivacyIndexRoute
  '/register': typeof publicRegisterIndexRoute
  '/terms': typeof publicTermsIndexRoute
  '/achievements': typeof AuthenticatedAchievementsIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/u/$username': typeof publicUUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/pay': typeof AuthenticatedPayRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/(public)/': typeof publicIndexRoute
  '/(public)/contact/': typeof publicContactIndexRoute
  '/(public)/cookies/': typeof publicCookiesIndexRoute
  '/(public)/leaderboard/': typeof publicLeaderboardIndexRoute
  '/(public)/login/': typeof publicLoginIndexRoute
  '/(public)/payments/': typeof publicPaymentsIndexRoute
  '/(public)/privacy/': typeof publicPrivacyIndexRoute
  '/(public)/register/': typeof publicRegisterIndexRoute
  '/(public)/terms/': typeof publicTermsIndexRoute
  '/_authenticated/achievements/': typeof AuthenticatedAchievementsIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/(public)/u/$username/': typeof publicUUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pay'
    | '/profile'
    | '/settings'
    | '/contact/'
    | '/cookies/'
    | '/leaderboard/'
    | '/login/'
    | '/payments/'
    | '/privacy/'
    | '/register/'
    | '/terms/'
    | '/achievements/'
    | '/dashboard/'
    | '/u/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pay'
    | '/profile'
    | '/settings'
    | '/contact'
    | '/cookies'
    | '/leaderboard'
    | '/login'
    | '/payments'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/achievements'
    | '/dashboard'
    | '/u/$username'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/pay'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/(public)/'
    | '/(public)/contact/'
    | '/(public)/cookies/'
    | '/(public)/leaderboard/'
    | '/(public)/login/'
    | '/(public)/payments/'
    | '/(public)/privacy/'
    | '/(public)/register/'
    | '/(public)/terms/'
    | '/_authenticated/achievements/'
    | '/_authenticated/dashboard/'
    | '/(public)/u/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  publicIndexRoute: typeof publicIndexRoute
  publicContactIndexRoute: typeof publicContactIndexRoute
  publicCookiesIndexRoute: typeof publicCookiesIndexRoute
  publicLeaderboardIndexRoute: typeof publicLeaderboardIndexRoute
  publicLoginIndexRoute: typeof publicLoginIndexRoute
  publicPaymentsIndexRoute: typeof publicPaymentsIndexRoute
  publicPrivacyIndexRoute: typeof publicPrivacyIndexRoute
  publicRegisterIndexRoute: typeof publicRegisterIndexRoute
  publicTermsIndexRoute: typeof publicTermsIndexRoute
  publicUUsernameIndexRoute: typeof publicUUsernameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pay': {
      id: '/_authenticated/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof AuthenticatedPayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achievements/': {
      id: '/_authenticated/achievements/'
      path: '/achievements'
      fullPath: '/achievements/'
      preLoaderRoute: typeof AuthenticatedAchievementsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(public)/terms/': {
      id: '/(public)/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof publicTermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/register/': {
      id: '/(public)/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof publicRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/privacy/': {
      id: '/(public)/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof publicPrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/payments/': {
      id: '/(public)/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof publicPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login/': {
      id: '/(public)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof publicLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/leaderboard/': {
      id: '/(public)/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard/'
      preLoaderRoute: typeof publicLeaderboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/cookies/': {
      id: '/(public)/cookies/'
      path: '/cookies'
      fullPath: '/cookies/'
      preLoaderRoute: typeof publicCookiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/contact/': {
      id: '/(public)/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof publicContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/u/$username/': {
      id: '/(public)/u/$username/'
      path: '/u/$username'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof publicUUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPayRoute: typeof AuthenticatedPayRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAchievementsIndexRoute: typeof AuthenticatedAchievementsIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPayRoute: AuthenticatedPayRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAchievementsIndexRoute: AuthenticatedAchievementsIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  publicIndexRoute: publicIndexRoute,
  publicContactIndexRoute: publicContactIndexRoute,
  publicCookiesIndexRoute: publicCookiesIndexRoute,
  publicLeaderboardIndexRoute: publicLeaderboardIndexRoute,
  publicLoginIndexRoute: publicLoginIndexRoute,
  publicPaymentsIndexRoute: publicPaymentsIndexRoute,
  publicPrivacyIndexRoute: publicPrivacyIndexRoute,
  publicRegisterIndexRoute: publicRegisterIndexRoute,
  publicTermsIndexRoute: publicTermsIndexRoute,
  publicUUsernameIndexRoute: publicUUsernameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
